### PR TITLE
[TH2-4915] Updated dependencies

### PR DESCRIPTION
**Pull request by Nikita-Smirnov-Exactpro**
[TH2-4987] Added com.gorylenko.gradle-git-properties plugin

[TH2-4987]: https://exactpro.atlassian.net/browse/TH2-4987?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by OptimumCode** [comment]
@Nikita-Smirnov-Exactpro can we close this PR? It looks like it contains outdated changes

**Comment by Nikita-Smirnov-Exactpro** [comment]
> @Nikita-Smirnov-Exactpro can we close this PR? It looks like it contains outdated changes

I'm OK but tests in this PR maybe useful

**Comment by OptimumCode** [comment]
Okay, I will rebase tests on the main branch

**Comment by Nikita-Smirnov-Exactpro** [comment]
> As I can see both tests are already added to the master branch
> 
> https://github.com/th2-net/th2-codec-json-dictionaryless/blob/master/src/test/kotlin/com/exactpro/th2/codec/json/EncodeTest.kt#L100 https://github.com/th2-net/th2-codec-json-dictionaryless/blob/master/src/test/kotlin/com/exactpro/th2/codec/json/DecodeTest.kt#L75
> 
> So, probably, we can close the PR

Thank you for checking

**Pull request closed without merging**
